"""add message

Revision ID: 6b434d432efb
Revises: 1f7ddb6b59c4
Create Date: 2025-11-10 19:31:15.674486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b434d432efb'
down_revision: Union[str, None] = '1f7ddb6b59c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('text', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('file_url', sa.String(length=1024), nullable=True))
    op.add_column('messages', sa.Column('audio_url', sa.String(length=1024), nullable=True))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.drop_constraint('messages_order_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'kind')
    op.drop_column('messages', 'order_id')
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('kind', postgresql.ENUM('TEXT', 'FILE', 'AUDIO', name='messagekind'), autoincrement=False, nullable=False))
    op.create_foreign_key('messages_order_id_fkey', 'messages', 'orders', ['order_id'], ['id'])
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'audio_url')
    op.drop_column('messages', 'file_url')
    op.drop_column('messages', 'text')
    # ### end Alembic commands ###
