"""complaints

Revision ID: 8d36d9807190
Revises: 6b434d432efb
Create Date: 2025-11-10 20:25:10.750602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d36d9807190'
down_revision: Union[str, None] = '6b434d432efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('link_id', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('complaints', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('complaints', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('complaints', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_complaints_link_id'), 'complaints', ['link_id'], unique=False)
    op.create_foreign_key(None, 'complaints', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'complaints', 'links', ['link_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_link_id'), table_name='complaints')
    op.alter_column('complaints', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('complaints', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('complaints', 'created_at')
    op.drop_column('complaints', 'created_by')
    op.drop_column('complaints', 'link_id')
    # ### end Alembic commands ###
